software-maestro-starting-blue/fourtooncookie-frontend

fourtoon-cookie/package-lock.json, fourtoon-cookie/package.json, fourtoon-cookie/src/components/common/BackButton/BackButton.styled.ts, fourtoon-cookie/src/components/common/BackButton/BackButton.tsx, fourtoon-cookie/src/components/common/BackButton/BackButtonStyles.ts
---
* 구현 내용
백버튼 컴포넌트 구현
버튼 위치는 스타일을 props에 전달해 외부에서 적용합니다.
=> [feat] 백버튼 컴포넌트 구현

fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
---
* 구현 내용
함수 이름을 handleOnPress -> handlePress
함수를 function에서 const로 변경
return하지 않고 즉시 실행
=> [style] 백버튼 핸들링 함수 수정

fourtoon-cookie/App.tsx, fourtoon-cookie/src/apis/api.ts, fourtoon-cookie/src/apis/character.ts, fourtoon-cookie/src/apis/diary.ts, fourtoon-cookie/src/apis/supabase.ts, fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateContext.tsx, fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx, fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx, fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
---
* 구현 내용
1. jwt 토큰 관리를 위해 refresh하는 로직을 추가하였습니다.
2. JwtToken을 검증하고 이를 통해 API를 전달할 수 있도록 api method를 추상화 하였습니다.
3. 이에 따라 여러 api method를 수정하고 이를 활용하는 부분도 적절하게 수정하였습니다.
1. 에러 관련 로직을 추가해야 합니다. 이는 TSK-246에서 대대적으로 실행될 예정입니다.
2. 시작 및 회원가입 페이지 구현을 통해 Jwt 토큰 관리를 더욱 철저하게 하는 로직을 구성해야 합니다. 이는 TSK-245에서 실행될 예정입니다.
---
실 구현이 아닌 그저 로직 추가이므로 화면 예시는 첨부하지 않겠습니다.
=> [feat] API 추상화 및 jwt 토큰 관리 로직 추가

fourtoon-cookie/App.tsx, fourtoon-cookie/src/components/global/GlobalCharacterList/GlobalCharacterListStateContext.tsx, fourtoon-cookie/src/components/global/GlobalCharacterList/GlobalCharacterListStateProvider.tsx, fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/Header/Header.tsx
---
* 구현 내용
캐릭터의 모든 정보를 Global로 다룰 수 있도록 하였습니다.
이에 따라서 다음 내용이 적용되었습니다.
1. CharacterSelectPage에서 캐릭터를 불러오는 로직이 단순화되었습니다.
2. DiaryTimelinePage에서 DiaryContent의 Header에 있는 Character 정보를 캐릭터 리스트를 통해 가지고 옵니다.
---
내부 로직 수정이기에 화면 예시는 생략하겠습니다.
=> [feat] GlobalCharacterListState 로직 추가

fourtoon-cookie/src/apis/api.ts, fourtoon-cookie/src/apis/appleOAuth.ts, fourtoon-cookie/src/apis/diary.ts, fourtoon-cookie/src/apis/googleOAuth.ts, fourtoon-cookie/src/apis/member.ts, fourtoon-cookie/src/apis/supabase.ts, fourtoon-cookie/src/components/global/GlobalCharacterList/GlobalCharacterListStateProvider.tsx, fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx, fourtoon-cookie/src/components/global/GlobalSelectionCharacter/GlobalSelectionCharacterStateProvider.tsx, fourtoon-cookie/src/systemcall/gpt.ts
---
* 구현 내용
에러 메시지 사용자 경험에 맞추어 변경
=> [refactor] 에러 메시지 변경

fourtoon-cookie/src/apis/diary.ts, fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
---
[refactor] patchDiary -> putDiary 변경
해시태그 관련된 내용 지워야함. (request, response 등)
=> [refactor] patchDiary -> putDiary 변경

fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.styled.ts, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.tsx
---
* 구현 내용
그림 완성이 안된 경우의 기능 추가
Character.interface
selectionThumbnailUrl(이미지) 이용
name(유료캐릭터) 이용
* 추 후 의논할 내용
현재 정적이고 추상적인 메시지 `열심히 작업 중입니다. 조금만 기다려주세요!` 로 표현했지만,
해당 페이지에 Diary 의 `imageUrls` 뿐 만 아니라, `createdDateTime`을 넘겨주고 활용해 `~ 시간 소요 예정입니다.` 라는 느낌으로 변경해도 좋아보임
=> [feat] 그림 완성이 안된 경우의 기능 추가

fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.tsx
=> [bug] DiaryPaintingImagesLayout에서 require 이중 중첩된 문제를 해결하였습니다.

fourtoon-cookie/src/types/gender.ts
---
* 구현 내용
Gender enum의 값을 소문자에서 대문자로 수정하였습니다.
=> [bug] Gender의 값을 소문자에서 대문자로 수정

fourtoon-cookie/src/apis/character.ts
---
* 구현 내용
캐릭터배열 응답값을 반환하는 과정에서 배열이 정상적으로 생기지 않는 오류 해결
---
=> [bug] 캐릭터 배열 변환 오류 해결

fourtoon-cookie/src/apis/diary.ts
---
* 구현 내용
백엔드의 응답에 맞추어 프론트엔드의 [GET] /diary/timeline 의 응답 처리 로직을 수정하였습니다.
=> [bug] get diaries 로직 수정

fourtoon-cookie/App.tsx, fourtoon-cookie/src/auth/jwt.ts
---
* 구현 내용
JWT Token이 있음에도 로드되지 않아서 항상 IntroPage에서 시작하던 문제를 해결하였습니다.
App.tsx에서 JWT Token이 로드 되기 전까지는 어플리케이션 내부 페이지를 로드하지 않도록 로직을 구성하였습니다.
=> [bug] JWT Token이 있음에도 로드되지 않아서 항상 IntroPage에서 시작하던 문제 해결

fourtoon-cookie/src/pages/SignUpPage/SignUpPage.tsx
---
fix: 회원가입 페이지 약관 동의시 안넘어가는 버그 수정
=> [bug]회원가입 페이지 약관 동의시 안넘어가는 버그 수정

fourtoon-cookie/src/components/layout/MainPageLayout/Footer/Footer.tsx, fourtoon-cookie/src/components/layout/MainPageLayout/MainPageLayout.tsx, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx, fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
---
* 구현 내용
- Footer가 항상 새로 불러와지는 문제를 개선하였습니다.
- Footer가 받는 prop을 간편하게 개선하였습니다.
=> [bug][refactor] 메인페이지 Footer 사용성 개선

fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
---
* 구현 내용
다른 페이지에서 돌아오면 DiaryTimelinePage 리프레시 되는 로직 추가
=> [bug][feat] 다른 페이지에서 돌아오면 DiaryTimelinePage 리프레시 되는 로직 추가

fourtoon-cookie/src/constants/agreement.ts, fourtoon-cookie/src/constants/appinfo.ts, fourtoon-cookie/src/constants/constants.ts, fourtoon-cookie/src/pages/SettingPage/MenuLayout/MenuLayout.tsx, fourtoon-cookie/src/pages/SignUpPage/AgreementInputLayout/AgreementInputLayout.tsx
---
* 구현 내용
- 노션 약관 및 개인정보 동의서 페이지 url 변수와 앱 정보 url 변수를 하나의 파일(appinfo.ts)에서 관리하도록 수정
- SettingPage의 '문의하기' -> '앱 정보'로 네이밍 수정
=> [bug] 문의하기 관련 리팩토링

fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryContentsLayout/DiaryContent/DiaryContent.tsx
---
* 구현 내용
기존에 어긋나있던 DiaryComponent의 더보기 여부 로직을 수정하였습니다.
=> [bug] diary content 더보기 오류 수정

fourtoon-cookie/src/constants/appinfo.ts, fourtoon-cookie/src/pages/SignUpPage/AgreementInputLayout/AgreementInputLayout.tsx
---
* 구현 내용
- 만 14세 이상임을 확인하는 로직을 추가했습니다.
- 약관과 개인정보처리동의서의 링크를 분리하여 적용하였습니다.
---
=> [bug] SignUpPage의 AgreementInputLayout 정책에 맞게 수정

fourtoon-cookie/src/auth/jwt.ts, fourtoon-cookie/src/components/global/GlobalSelectionCharacter/GlobalSelectionCharacterStateProvider.tsx, fourtoon-cookie/src/error/errorhandler.ts, fourtoon-cookie/src/pages/IntroPage/GoogleSignInAndSignUpButton/GoogleSignInAndSignUpButton.tsx
- [] merge (병합)
---
* 구현 내용
---
=> hotfix: consol.log 제거

fourtoon-cookie/App.tsx, fourtoon-cookie/src/store/member.ts
---
* 구현 내용
member가 직접적으로 jwt를 사용하게 되면서 회원가입이 안 되는 문제가 발생하였습니다.
(곧, SignUpPage로 넘어가지지 않았던 문제가 있었습니다.)
jwt가 존재하지만, Member가 존재하지 않을 때 해당 오류가 발생했습니다.
따라서 member에서 reload를 진행할 경우에는 jwt를 건드리지 않도록 로직을 수정하였습니다.
=> [fix] 회원가입 안 되는 오류 해결

fourtoon-cookie/src/pages/SignUpPage/NameInputLayout/NameInputLayout.tsx, fourtoon-cookie/src/pages/SignUpPage/SignUpPage.tsx
---
* 구현 내용
SignUpPage에서 '이름'으로 사용되던 항목을 '닉네임'으로 변경하였습니다.
---
=> [feat] SignUpPage에서 이름 -> 닉네임

fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx, fourtoon-cookie/src/pages/CharacterSelectPage/TabsLayout/TabsLayout.tsx
현재 BM 설정을 진행하지 않았기에 유료 탭을 주석처리하였습니다.
애플 심사 리뷰 반영.
---
=> [feat] 캐릭터 유료 탭 삭제

fourtoon-cookie/src/pages/IntroPage/AppleSignInAndSignUpButton/AppleSignInAndSignUpButton.tsx, fourtoon-cookie/src/pages/IntroPage/GoogleSignInAndSignUpButton/GoogleSignInAndSignUpButton.tsx, fourtoon-cookie/src/pages/IntroPage/IntroPage.tsx
---
* 구현 내용
- IntroPage의 컴포넌트를 리팩토링 하였습니다
- IntroPage의 두 버튼에서 발생한 공통 로직을 정리하였습니다.
=> [refactor] IntroPage 리팩터링 진행

fourtoon-cookie/src/constants/routing.ts, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryComponent.tsx, fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx, fourtoon-cookie/src/pages/DiaryWritePage/Header/Header.tsx, fourtoon-cookie/src/pages/DiaryWritePage/WriteDoneButtonLayout/WriteDoneButtonLayout.styled.ts, fourtoon-cookie/src/pages/DiaryWritePage/WriteDoneButtonLayout/WriteDoneButtonLayout.tsx
---
* 구현 내용
- DiaryWritePage의 컴포넌트들을 리팩토링하였습니다
(구체적인 내용은 커밋에서 확인 가능합니다.)
=> [refactor] DiaryWritePage 리팩토링 진행

fourtoon-cookie/App.tsx, fourtoon-cookie/src/hooks/account.ts, fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx, fourtoon-cookie/src/pages/DiaryWritePage/WriteDoneButtonLayout/WriteDoneButtonLayout.tsx, fourtoon-cookie/src/pages/IntroPage/IntroPage.tsx, fourtoon-cookie/src/pages/SettingPage/MenuLayout/MenuLayout.tsx, fourtoon-cookie/src/pages/SettingPage/ProfileLayout/ProfileLayout.tsx, fourtoon-cookie/src/store/account.ts, fourtoon-cookie/src/store/diaryList.ts
---
* 구현 내용
- 회원가입이나 로그인이 없어도 기능 일부를 확인해볼 수 있도록 수정하였습니다.
- 첫 페이지를 DiaryTimelinePage로 설정하였습니다.
- DiaryWritePage에서 비로그인 상태로 작성 버튼을 누르면, IntroPage로 라우팅 되도록 수정하였습니다.
- SettingPage에서 비로그인 시 로그인 버튼이 보이도록 로직을 수정하였습니다.
---
=> [feat] 회원가입 혹은 로그인이 필수가 아니도록 로직 수정

fourtoon-cookie/App.tsx, fourtoon-cookie/src/apis/api.ts
---
* 구현 내용
- getCharacters를 호출할 때도 jwt를 요청하여서 비로그인시 character가 나타나지 않던 오류를 수정했습니다
- requestApi에서 우선적으로 jwt를 보지 않도록 로직을 구성하였습니다.
=> [fix] getCharacter에서 무조건적으로 jwt 요구하던 오류 수정

fourtoon-cookie/App.tsx, fourtoon-cookie/package-lock.json, fourtoon-cookie/package.json
---
* 구현 내용
sentry 로깅 추가
에러가 발생하는 경우 sentry에 로깅
---
=> [feat] sentry 로깅 추가

fourtoon-cookie/App.tsx, fourtoon-cookie/package-lock.json, fourtoon-cookie/package.json, fourtoon-cookie/src/pages/DiaryWritePage/WriteDoneButtonLayout/WriteDoneButtonLayout.tsx, fourtoon-cookie/src/system/amplitude.ts
---
* 구현 내용
amplitude 로깅을 추가했습니다.
App.tsx에서 init한 후에 사용이 가능합니다.
우선은 일기 작성 시 일기를 작성했다는 정보와 함께 선택한 캐릭터 정보를 전송합니다.
참고: https://amplitude.com/docs/sdks/analytics/react-native/react-native-sdk
---
=> [feat] amplitude 로깅 추가

fourtoon-cookie/src/components/error/ErrorComponent/ErrorComponent.tsx
---
* 구현 내용
- 에러 컴포넌트 스타일 인자 실수 해결
=> [bug] 에러 컴포넌트 스타일 인자 실수 해결

fourtoon-cookie/src/apis/api.ts
---
* 구현 내용
1. Header에 Accept-Language를 추가하여 API request를 보낼 때마다 사용자의 언어 정보를 같이 보내도록 로직을 구성하였습니다.
=> [feat] 백엔드에 언어 정보 보내도록 Api request 설정

fourtoon-cookie/locales/en.json, fourtoon-cookie/locales/ko.json, fourtoon-cookie/src/pages/DiaryWritePage/WriteDoneButtonLayout.tsx
---
* 구현 내용
1. 국제화 진행하면서 오탈자가 발생해 오류가 발생하는 부분이 있어서 해당 부분을 수정하였습니다.
1. 추후에는 코드 상에서 오류를 감지할 수 있도록 코드 레벨에서 해당 언어들을 구현할 필요성은 있어보입니다.
=> [bug] 국제화 오탈자 오류 수정

fourtoon-cookie/App.tsx, fourtoon-cookie/package-lock.json, fourtoon-cookie/package.json, fourtoon-cookie/src/types/routing.ts
---
* 구현 내용
@react-navigation/bottom-tabs 의존성을 추가하였습니다.
1. DiaryTimelinePage와 SettingPage에서는 서로 백버튼이 작용하지 않도록 로직 구성
StackScreen 안에다가 Tabs(DiaryTimelinePage와 SettingPage)를 따로 두어서 Tabs 끼리는 백버튼이 되지 않고 StackScreen 자체가 바뀔 때는 백버튼이 동작하도록 로직을 수정하였습니다.
---
동적인 로직이어서 증명하기 어려워서 직접 구동해보시기를 추천드립니다.
=> [feat] DiaryTimelinePage와 SettingPage에서는 서로 백버튼이 작용하지 않도록 로직 구성
